### ISSUE TITLE
Does not work in El Capitan or Sierra

### ISSUE THREAD

**Issue by mcdado** [josh-/CloudyTabs#33] opened 2015-11-26 22:06 UTC
The app launches, but the menubar icon is not responsive to any type of click.
After launch, I can see two identical successive messages in Console.app:

```
26/11/15 23:04:32,746 CloudyTabs[30513]: -[__NSCFArray objectForKeyedSubscript:]: unrecognized selector sent to instance 0x7fa1c2c72c60
```

**Comment by sillygwailo** [comment] 2016-01-12 16:55
I have the same experience. CloudyTabs version 1.6 doesn't work at all on OS X version 10.11.2.

**Comment by josh-** [comment] 2016-01-25 12:40
Thanks very much for reporting this guys – it works fine here on my end (OS X 10.11.3) so I'm struggling to reproduce this issue. If you'd be happy to share any relevant crash logs with me (usually stored in `~/Library/Logs/DiagnosticReports/`) that would be an immense help!

**Comment by sillygwailo** [comment] 2016-01-25 14:50
@josh- Are there any other logs we can provide? It doesn't exactly crash, but is just unusable. I can only quit out of it by going into Activity Monitor and force-quitting the process.

**Comment by mcdado** [comment] 2016-01-25 14:52
Yep, the menubar icon basically does nothing on click.

**Comment by sillygwailo** [comment] 2016-03-24 17:38
Still true on 10.11.4. Here are the messages I get in Console.

```
3/24/16 1:35:39.026 PM CloudyTabs[10092]: -[__NSCFArray objectForKeyedSubscript:]: unrecognized selector sent to instance 0x7fd431e4c850
3/24/16 1:35:39.026 PM CloudyTabs[10092]: -[__NSCFArray objectForKeyedSubscript:]: unrecognized selector sent to instance 0x7fd431e4c850
```

No crash logs titled with "CloudyTabs" in ~/Library/Logs/DiagnosticReports/.

**Comment by LaserBears** [comment] 2016-06-01 04:22
Seeing this on 10.11.5, but with two different (hopefully more helpful) messages in the console:

    CloudyTabs[15019]: *** Assertion failure in -[NSMenuItem initWithTitle:action:keyEquivalent:], /Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1404.47/Menus.subproj/NSMenuItem.m:402
    CloudyTabs[15019]: Invalid parameter not satisfying: aString != nil

**Comment by MarkEstefanos** [comment] 2016-07-01 01:28
Also getting this issue.

**Comment by dhalarewich** [comment] 2016-07-12 18:57
Getting the same issue here on 10.11.5. Here's the messages that I'm seeing in console:

``` CloudyTabs[1958]: *** Assertion failure in -[NSMenuItem initWithTitle:action:keyEquivalent:], /Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1404.47/Menus.subproj/NSMenuItem.m:402
 CloudyTabs[1958]: Invalid parameter not satisfying: aString != nil```

**Comment by jadchaar** [comment] 2016-07-21 20:14
Had this issue on my old Mac (running El Capitan) and I recently got a new Mac, and the issue is still present. The menu bar icon used to at least click on my old machine, but nothing would come up when the icon is clicked.. Now, on my new Mac (clean install), the menubar app doesn't even open when I click the icon. No press feedback or anything. It is like I am not clicking anything.

This is a video depicting the behavior. This video was recorded after a fresh install and first startup after dragging to applications. Nothing occurring in the console when icon clicked. Video located in [this zip file](https://github.com/josh-/CloudyTabs/files/376877/bug.zip). Thanks!

**Comment by LaserBears** [comment] 2016-08-09 19:39
After investigating a bit further, it looks like Apple now encrypts the iCloud tabs data in `~/Library/SyncedPreferences/com.apple.Safari.plist` (there are `remotevalue`, `com.apple.Safari.EncryptedKVS.PCSEncryptedData`, and `com.apple.Safari.EncryptedKVS.PCSObject` entries for each device containing binary data).

So unfortunately, unless someone can figure out how to decrypt that data then this app and others like it that rely on reading the iCloud tabs from `~/Library/SyncedPreferences/com.apple.Safari.plist` are dead in the water.

**Comment by nehayward** [comment] 2016-10-13 23:13
Any ideas on how to decrypt it?

**Comment by josh-** [comment] 2016-11-16 06:30
I haven't successfully been able to decrypt the data yet unfortunately. It appears that Apple is now using CloudKit to sync the preferences, as there are references to PCS decryption in the [CloudKitDaemon framework](https://github.com/hughbe/macOS-iOS-headers/blob/5999d4162a956b30df8886ca1297c415e9621090/macOS/PrivateFrameworks/CloudKitDaemon.framework/CKShareMetadata-CKDaemonExtensions.h#L10) – it might be possible to use that private framework to decrypt the data?

Alternatively it might be possible to go down the route of interacting with the API as [this project](https://github.com/smpanaro/icloud-tabs/) attempted to do a while ago – there is a good writeup of the Protobuf API [here](https://github.com/horrorho/InflatableDonkey/blob/master/CloudKit.md). However, I'm not in favour of this option at all as it probably violates the TOS.

I'm not sure how much spare time I'll have to be able to investigate, but hopefully someone will be able to figure it out eventually 👍

**Comment by josh-** [comment] 2017-10-18 03:08
Fixed in https://github.com/josh-/CloudyTabs/commit/4b64bd19f9b59730d5956c5661c9e1c377864757 👍

**Closed by josh-** 2017-10-18 03:08 UTC
Labels: bug
