### ISSUE TITLE
Add "Save tabs from x as text file" feature

### ISSUE THREAD

**Issue by ondono** [josh-/CloudyTabs#55] opened 2019-02-13 08:54 UTC
After 2 days of search,  asking on [Ask different](https://apple.stackexchange.com/questions/350908/getting-a-text-file-with-the-url-of-open-tabs), on the Apple support forums, etc... I came across CloudyTabs. I've seen that I am not the only one that fills the safari tabs on my iphone pretty badly.

Using CloudyTabs will most likely freeze my macbook, since I'm over 300 tabs, but It occured to me that this app should be able to generate such a text file. I'll be looking into this to see if it's a useful enhancement.

**Comment by dweade** [comment] 2019-02-14 01:36
I was just on here to request a feature like this. I've been having issues with Chrome not opening more than @25 URLs from Cloudytab and found Firefox was handling this fine, so I switched over everything this week. 

What did fork for me, that ondono might try, was opening all the tabs (58 in my case) and keep hotkeying a new browser window every 30 or so. Then, use OneTab to funnel all of them to a collection (OneTab creates a text list of tabs you can open later). Most tabs were still loading when they were funneled off but you do have to wait until all the links are opened from Cloudytab or else the new tabs will open in whichever browser page is active. It's possible your computer would bog down before 300 can be opened.

Using OneTab just now made me think of such a list and being able to drop it into OneTab's page of lists would work right into my workflow.

How OneTab's export/import list appears (which is just a list):
https://github.com/josh-/CloudyTabs | josh-/CloudyTabs: CloudyTabs is a simple menu bar application that lists your iCloud Tabs.
https://github.com/josh-/CloudyTabs/pulls | Pull Requests · josh-/CloudyTabs
https://github.com/josh-/CloudyTabs/projects | Projects · josh-/CloudyTabs

Thanks

**Comment by ondono** [comment] 2019-03-26 08:33
I actually went and used cloudy tabs to open all ~400 tabs and ran the script.

My i7 suffered a little, and some of the tabs appeared as "Error: safari could not load the resource", so I had to repeat the process and do a lot of file cleaning and manually checked that all pages were there. A little bit tedious but it was done in 40 min.

I've now cleaned my phone, and set up a calendar alarm to empty the backlog every 2 weeks. Now I just need to find a way to automate consolidation and to ease organization (maybe tabs). I've I figure out something I'll be sure to ping back to this issue for others in this situation.

**Comment by cliffordp** [comment] 2020-05-18 16:45
Duplicate of https://github.com/josh-/CloudyTabs/issues/40

**Comment by cliffordp** [comment] 2020-05-18 18:33
This worked for me for the maximum 500 tabs on iPhone, without having to open any of them on Mac (my biggest concern, for performance and dropping any) -- **no CloudyTabs needed:**
1. Have no bookmarks in Safari to start (recommended, not required)
1. Add all iPhone open tabs [as a folder of bookmarks](https://www.idownloadblog.com/2019/08/02/safari-save-all-open-tabs-bookmarks-iphone-ipad/) (long-press the _Bookmarks_ icon on iPhone Safari)
1. Safari > File > Export Bookmarks
1. Chrome > Import Bookmarks and Settings (the auto-importer from Safari didn't work for me)
1. Chrome > Bookmarks > Bookmark Manager > verify the Safari export got imported successfully
1. Safari > Bookmarks > Edit Bookmarks > delete the folder
1. Long-press the Tabs icon on iPhone and close ALL tabs (scary but feels good)
1. Use whichever variety of Chrome tools/extensions to do what you will (open all links within a specific bookmark folder, export to text, etc.)

**Comment by josh-** [comment] 2020-09-30 11:57
Hey everyone, I've just released [Version 2.0](https://github.com/josh-/CloudyTabs/releases/tag/v2.0) which includes support for exporting tabs from each device to a CSV file.

Please let me know if you have feedback on the feature 😄

**Closed by josh-** 2020-09-30 11:57 UTC

**Comment by mcdado** [comment] 2020-12-03 10:48
> Hey everyone, I've just released [Version 2.0](https://github.com/josh-/CloudyTabs/releases/tag/v2.0) which includes support for exporting tabs from each device to a CSV file.
> 
> From CloudyTabs go to 'Export All Tabs From', select your device and then choose a filename.
> 
> Please let me know if you have feedback on the feature 😄

Thank you! It's a very good idea, and it's implemented well! It would be nice if the same feature could be added for reading list!

Also, maybe there should be a limit of bookmarks in the list before they get pushed in a submenu, for example i have 6 page-down amounts of links. They options for exporting are at the bottom. Maybe say, show in the list until there are 20 otherwise use a submenu?
